plugins:
  - "@typescript-eslint"
  - testing-library
  - cypress
env:
  browser: true
  node: true
parserOptions:
  ecmaVersion: 2020
  sourceType: module
extends:
  - eslint:recommended
  - plugin:testing-library/dom
  - "plugin:@next/next/recommended"
  - "plugin:react/recommended"
  - "plugin:react/jsx-runtime"
settings:
  "import/resolver":
    "node":
      "extensions": [".js", ".jsx", ".ts", ".tsx"]
rules:
  comma-dangle:
    - error
    - always-multiline
  consistent-return: error
  indent:
    - error
    - 4
    - SwitchCase: 1
  quotes: error
  semi: error
  keyword-spacing: error
  space-before-blocks: error
  no-multiple-empty-lines:
    - error
    - max: 1
      maxBOF: 0
      maxEOF: 0
  no-multi-spaces: error
overrides:
  - files: [ "**/*.tsx", "**/*.ts" ]
    extends:
      - plugin:cypress/recommended
    rules:
     "testing-library/await-async-utils": "off"
