name: Node.js CI

on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 21
        uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: "yarn"
      - run: yarn install --immutable --immutable-cache --check-cache
      - run: yarn lint
      - run: yarn build
        env:
          SENTRY_ENVIRONMENT: ${{ github.ref_name == 'main' && 'production' || 'staging' }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_RELEASE: ${{ github.sha }}
          NEXT_PUBLIC_SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          NEXT_PUBLIC_EAB_HOST: 'https://eab.api.hm.edu'
          NEXT_PUBLIC_ACME_HOST: 'https://acme.hm.edu'
          NEXT_PUBLIC_PKI_HOST: 'https://pki.api.hm.edu'
          NEXT_PUBLIC_DOMAIN_HOST: 'https://domain.api.hm.edu'
          NEXT_PUBLIC_AUTH_IDP: 'https://sso.hm.edu'
          NEXT_PUBLIC_ORGANIZATION_NAME: 'Hochschule München'
          NEXT_PUBLIC_DOCS_URL: 'https://conwiki.cc.hm.edu/confluence/pages/viewpage.action?pageId=198048309'

  e2e:
    runs-on: ubuntu-22.04
    container:
     image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
     options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
      - name: Cypress run
        id: cypress
        uses: cypress-io/github-action@v6
        with:
          build: yarn build
          start: yarn start
          record: true
        env:
          # pass the Cypress Cloud record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # pass the project ID from the secrets through environment variable
          CYPRESS_PROJECT_ID: ${{ secrets.PROJECT_ID }}
          NEXT_PUBLIC_DISABLE_CSP: true
          NEXT_PUBLIC_EAB_HOST: 'https://eab.api.hm.edu'
          NEXT_PUBLIC_ACME_HOST: 'https://acme.hm.edu'
          NEXT_PUBLIC_PKI_HOST: 'https://pki.api.hm.edu'
          NEXT_PUBLIC_DOMAIN_HOST: 'https://domain.api.hm.edu'
          NEXT_PUBLIC_AUTH_IDP: 'https://sso.hm.edu'
          NEXT_PUBLIC_ORGANIZATION_NAME: 'Hochschule München'
          NEXT_PUBLIC_DOCS_URL: 'https://conwiki.cc.hm.edu/confluence/pages/viewpage.action?pageId=198048309'
          HOST: "0.0.0.0"
          NEXT_PUBLIC_CI: "true"
        continue-on-error: true
      - uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
      - name: Check on failures
        if: steps.cypress.outcome == 'failure'
        run: exit 1
  docker:
    runs-on: ubuntu-latest
    needs: e2e
    env:
      # Use docker.io for Docker Hub if empty
      REGISTRY: ghcr.io
      # github.repository as <account>/<repo>
      IMAGE_NAME: hm-edu/portal-frontend
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=raw,value={{branch}}-{{sha}}-{{date 'X'}},enable=${{ github.event_name != 'pull_request' }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' && github.actor != 'dependabot[bot]' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          secrets: |
            SENTRY_ENVIRONMENT=${{ github.ref_name == 'main' && 'production' || 'staging' }}
            SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
            SENTRY_RELEASE=${{ github.sha }}
            NEXT_PUBLIC_SENTRY_DSN=${{ secrets.SENTRY_DSN }}
            NEXT_PUBLIC_EAB_HOST=https://eab.api.hm.edu
            NEXT_PUBLIC_ACME_HOST=https://acme.hm.edu
            NEXT_PUBLIC_PKI_HOST=https://pki.api.hm.edu
            NEXT_PUBLIC_DOMAIN_HOST=https://domain.api.hm.edu
            NEXT_PUBLIC_AUTH_IDP=https://sso.hm.edu
            NEXT_PUBLIC_ORGANIZATION_NAME=Hochschule München
            NEXT_PUBLIC_DOCS_URL=https://conwiki.cc.hm.edu/confluence/pages/viewpage.action?pageId=198048309
