name: Node.js CI

on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: "yarn"
      - run: yarn install --immutable --immutable-cache --check-cache
      - run: yarn lint
      - run: yarn build
        env:
          SENTRY_ENVIRONMENT: ${{ github.ref_name == 'main' && 'production' || 'staging' }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_RELEASE: ${{ github.sha }}
          NEXT_PUBLIC_SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          NEXT_PUBLIC_EAB_HOST: ${{ github.ref_name == 'main' && 'https://eab.api.hm.edu' || 'https://eab.api.hmtest.de' }}
          NEXT_PUBLIC_ACME_HOST: ${{ github.ref_name == 'main' && 'https://acme.hm.edu' || 'https://acme.hmtest.de' }}
          NEXT_PUBLIC_PKI_HOST: ${{ github.ref_name == 'main' && 'https://pki.api.hm.edu' || 'https://pki.api.hmtest.de' }}
          NEXT_PUBLIC_DOMAIN_HOST: ${{ github.ref_name == 'main' && 'https://domain.api.hm.edu' || 'https://domain.api.hmtest.de' }}
          NEXT_PUBLIC_AUTH_IDP: ${{ github.ref_name == 'main' && 'https://sso.hm.edu' || 'https://sso.hm.edu' }}
          NEXT_PUBLIC_ORGANIZATION_NAME: ${{ github.ref_name == 'main' && 'Hochschule M端nchen' || 'Hochschule M端nchen' }}
  
  e2e:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          build: yarn build
          start: yarn start
          wait-on: http://localhost:3000
      - uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: cypress/videos
    
  docker:
    runs-on: ubuntu-latest
    needs: e2e
    env:
      # Use docker.io for Docker Hub if empty
      REGISTRY: ghcr.io
      # github.repository as <account>/<repo>
      IMAGE_NAME: ${{ github.repository }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=raw,value={{branch}}-{{sha}}-{{date 'X'}},enable=${{ github.event_name != 'pull_request' }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' && github.actor != 'dependabot[bot]' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          secrets: |
            SENTRY_ENVIRONMENT=${{ github.ref_name == 'main' && 'production' || 'staging' }}
            SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
            SENTRY_RELEASE=${{ github.sha }}
            NEXT_PUBLIC_SENTRY_DSN=${{ secrets.SENTRY_DSN }}
            NEXT_PUBLIC_EAB_HOST=${{ github.ref_name == 'main' && 'https://eab.api.hm.edu' || 'https://eab.api.hmtest.de' }}
            NEXT_PUBLIC_ACME_HOST=${{ github.ref_name == 'main' && 'https://acme.hm.edu' || 'https://acme.hmtest.de' }}
            NEXT_PUBLIC_PKI_HOST=${{ github.ref_name == 'main' && 'https://pki.api.hm.edu' || 'https://pki.api.hmtest.de' }}
            NEXT_PUBLIC_DOMAIN_HOST=${{ github.ref_name == 'main' && 'https://domain.api.hm.edu' || 'https://domain.api.hmtest.de' }}
            NEXT_PUBLIC_AUTH_IDP=${{ github.ref_name == 'main' && 'https://sso.hm.edu' || 'https://sso.hm.edu' }}
            NEXT_PUBLIC_ORGANIZATION_NAME=${{ github.ref_name == 'main' && 'Hochschule M端nchen' || 'Hochschule M端nchen' }}
